// Traces the chosen emblem to vector: generated/emblem/emblem.svg (for reference)
// and lib/content/emblem-path.ts for the 3D extrusion.
//   node scripts/emblem-trace.mjs generated/emblem/scales.png
import { writeFileSync } from "node:fs";
import potrace from "potrace";
import sharp from "sharp";
const src = process.argv[2] ?? "generated/emblem/scales.png";
const png = await sharp(src).resize(1024, 1024).grayscale().png().toBuffer();
const svg = await new Promise((res, rej) =>
  potrace.trace(png, { threshold: 140, blackOnWhite: false, turdSize: 80, optTolerance: 0.35, alphaMax: 1, color: "#ffffff", background: "transparent" }, (e, s) => (e ? rej(e) : res(s))),
);
const d = svg.match(/ d="([^"]+)"/)[1];
const w = Number(svg.match(/width="(\d+)/)[1]), h = Number(svg.match(/height="(\d+)/)[1]);
// Tight bounding box from the path numbers
const nums = d.match(/-?\d+(?:\.\d+)?/g).map(Number);
let x1 = Infinity, y1 = Infinity, x2 = -Infinity, y2 = -Infinity;
for (let i = 0; i + 1 < nums.length; i += 2) { const x = nums[i], y = nums[i + 1]; if (x < x1) x1 = x; if (x > x2) x2 = x; if (y < y1) y1 = y; if (y > y2) y2 = y; }
writeFileSync("generated/emblem/emblem.svg", `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x1.toFixed(0)} ${y1.toFixed(0)} ${(x2 - x1).toFixed(0)} ${(y2 - y1).toFixed(0)}"><path fill="currentColor" fill-rule="evenodd" d="${d}"/></svg>`);
writeFileSync("lib/content/emblem-path.ts", `// Generated by scripts/emblem-trace.mjs from the chosen emblem candidate.\nexport const emblemPath = ${JSON.stringify(d)};\nexport const emblemBox = ${JSON.stringify({ x1, y1, x2, y2 })};\nexport const emblemViewBox = "${x1.toFixed(0)} ${y1.toFixed(0)} ${(x2 - x1).toFixed(0)} ${(y2 - y1).toFixed(0)}";\n`);
console.log("traced", d.length, "chars", { w, h, x1, y1, x2, y2 });
