// The motif library. Fictional studio, real iconography. Each entry is
// written in our own words; `image` is empty until artwork exists, and the
// MotifPlate component renders the kanji as the visual meanwhile.

export type MotifCategory = "creature" | "flower" | "water" | "guardian" | "background";
export type Method = "tebori" | "machine" | "both";
export type Tone = "paper" | "deep" | "ink";

export type Motif = {
  slug: string;
  name: string;
  ja: string;
  reading: string;
  kanji: string;
  category: MotifCategory;
  meaning: string;
  lore: string;
  sessions: [number, number];
  placements: string[];
  pairsWith: string[];
  method: Method;
  tone: Tone;
  image?: string;
  /** Photo of the motif tattooed on the body (scripts/worn-art.mjs) */
  worn?: string;
  /** Where it sits in that photo, for the image description */
  wornOn?: string;
};

export const categories: { id: MotifCategory; label: string; ja: string }[] = [
  { id: "creature", label: "Creatures", ja: "生き物" },
  { id: "flower", label: "Flowers", ja: "花" },
  { id: "water", label: "Water & wind", ja: "水風" },
  { id: "guardian", label: "Guardians", ja: "守護" },
  { id: "background", label: "Backgrounds", ja: "背景" },
];

export const methods: { id: Method; label: string; ja: string }[] = [
  { id: "tebori", label: "Tebori", ja: "手彫り" },
  { id: "machine", label: "Machine", ja: "機械彫り" },
  { id: "both", label: "Either", ja: "両方" },
];

const raw: Motif[] = [
  {
    slug: "koi",
    name: "Koi",
    ja: "鯉",
    reading: "koi",
    kanji: "鯉",
    category: "creature",
    meaning: "Perseverance. The carp that climbs the waterfall becomes a dragon.",
    lore: "Swimming upstream means struggle still under way; swimming down means the struggle is won. Ask which one you want before the outline goes on. Black, red and gold are the traditional colours, and a single koi on the forearm is one of the most common first large pieces in the studio.",
    sessions: [2, 6],
    placements: ["Forearm", "Calf", "Ribs", "Back"],
    pairsWith: ["nami", "momiji", "hasu"],
    method: "both",
    tone: "paper",
  },
  {
    slug: "ryu",
    name: "Dragon",
    ja: "龍",
    reading: "ryū",
    kanji: "龍",
    category: "creature",
    meaning: "Wisdom and protection. A water spirit, never a beast of fire.",
    lore: "The Japanese dragon has three claws, a long body and no wings, and it lives in rivers and clouds rather than caves. It is benevolent: a guardian, a bringer of rain. On a back piece the body wraps the shoulder and the head sits over the shoulder blade so it reads from across a room.",
    sessions: [6, 20],
    placements: ["Back", "Full sleeve", "Chest and arm"],
    pairsWith: ["kumo", "nami", "kiku"],
    method: "tebori",
    tone: "ink",
  },
  {
    slug: "tora",
    name: "Tiger",
    ja: "虎",
    reading: "tora",
    kanji: "虎",
    category: "creature",
    meaning: "Courage, and a guard against bad luck and disease.",
    lore: "Tigers were never native to Japan, so the classical drawings came from Chinese paintings, which gives them their flat, patterned faces. Paired with bamboo they stand for strength that bends. Usually placed where the stripes can follow a muscle.",
    sessions: [4, 12],
    placements: ["Thigh", "Ribs", "Half sleeve", "Back"],
    pairsWith: ["take", "kaze", "momiji"],
    method: "both",
    tone: "deep",
  },
  {
    slug: "hebi",
    name: "Snake",
    ja: "蛇",
    reading: "hebi",
    kanji: "蛇",
    category: "creature",
    meaning: "Renewal and protection. Sheds its skin, keeps its secrets.",
    lore: "Snakes guard treasure and ward off illness; a white snake is a messenger of Benzaiten. Their length makes them the easiest large creature to fit around a limb, and they pair naturally with flowers that need something to coil through.",
    sessions: [3, 8],
    placements: ["Forearm", "Calf", "Around the thigh"],
    pairsWith: ["botan", "kiku", "sakura"],
    method: "both",
    tone: "paper",
  },
  {
    slug: "tsuru",
    name: "Crane",
    ja: "鶴",
    reading: "tsuru",
    kanji: "鶴",
    category: "creature",
    meaning: "Long life and fidelity. Cranes are said to live a thousand years.",
    lore: "Cranes pair for life, which is why they appear at weddings. In tattooing they are drawn in flight with the neck stretched, feathers as long clean lines. A quiet motif that suits shoulders and chest plates.",
    sessions: [2, 5],
    placements: ["Shoulder", "Chest", "Upper back"],
    pairsWith: ["matsu", "kumo", "ume"],
    method: "machine",
    tone: "paper",
  },
  {
    slug: "kitsune",
    name: "Fox",
    ja: "狐",
    reading: "kitsune",
    kanji: "狐",
    category: "creature",
    meaning: "Cunning and the divine. Messenger of Inari, shape-shifter, trickster.",
    lore: "The fox mask is a popular modern motif, the animal itself the older one. Nine tails mean age and power. White foxes belong to the shrine; red foxes to the folktales. Often drawn with fire (kitsunebi) at the tips of the tails.",
    sessions: [2, 6],
    placements: ["Forearm", "Calf", "Shoulder"],
    pairsWith: ["momiji", "kumo", "sakura"],
    method: "both",
    tone: "paper",
  },
  {
    slug: "karajishi",
    name: "Foo dog",
    ja: "唐獅子",
    reading: "karajishi",
    kanji: "獅子",
    category: "guardian",
    meaning: "Protection. The lion-dog that guards the gate and drives off evil.",
    lore: "Lions came to Japan as an idea, not an animal, which is why the karajishi has curls for a mane and a face like a mask. Traditionally paired with peonies, the king of flowers, a pairing so fixed it has its own name. Works at any size from a hand to a full back.",
    sessions: [3, 10],
    placements: ["Shoulder", "Thigh", "Back"],
    pairsWith: ["botan", "kaze", "iwa"],
    method: "both",
    tone: "deep",
  },
  {
    slug: "botan",
    name: "Peony",
    ja: "牡丹",
    reading: "botan",
    kanji: "牡丹",
    category: "flower",
    meaning: "The king of flowers: wealth, boldness, a full life.",
    lore: "Big, layered and unapologetic. Peonies fill gaps in large work and carry a whole forearm on their own. Red is the classic, but pink, white and a deep wine all read well on skin. Petals are one of the places tebori shading shows most.",
    sessions: [1, 4],
    placements: ["Forearm", "Shoulder", "Hip", "Filler in large work"],
    pairsWith: ["karajishi", "hebi", "kaze"],
    method: "tebori",
    tone: "paper",
  },
  {
    slug: "sakura",
    name: "Cherry blossom",
    ja: "桜",
    reading: "sakura",
    kanji: "桜",
    category: "flower",
    meaning: "Beauty in transience. Here, then gone.",
    lore: "Cherry blossoms fall at their peak, which is the whole point. Rarely a centrepiece; almost always scattered through a piece to carry the eye from one element to the next, or placed alone as a small first tattoo.",
    sessions: [1, 3],
    placements: ["Anywhere as filler", "Wrist", "Collarbone"],
    pairsWith: ["koi", "kitsune", "kaze"],
    method: "both",
    tone: "paper",
  },
  {
    slug: "kiku",
    name: "Chrysanthemum",
    ja: "菊",
    reading: "kiku",
    kanji: "菊",
    category: "flower",
    meaning: "Longevity, and the crest of the imperial house. Autumn's flower.",
    lore: "Drawn as a radiating circle of narrow petals, which makes it the most geometric of the flowers and the one that sits best on a knee, shoulder or elbow. Often used to cap a sleeve.",
    sessions: [1, 4],
    placements: ["Shoulder cap", "Knee", "Elbow", "Chest"],
    pairsWith: ["ryu", "hebi", "kaze"],
    method: "both",
    tone: "paper",
  },
  {
    slug: "momiji",
    name: "Maple leaves",
    ja: "紅葉",
    reading: "momiji",
    kanji: "紅葉",
    category: "flower",
    meaning: "The turning of the year. Leaves in the water, autumn light.",
    lore: "Maple leaves are what you add to koi and water when the piece needs warmth. They float, they scatter, they are quick to tattoo and forgiving to heal, and they give a cold piece a season.",
    sessions: [1, 2],
    placements: ["Filler in water pieces", "Forearm", "Ankle"],
    pairsWith: ["koi", "nami", "tora"],
    method: "both",
    tone: "paper",
  },
  {
    slug: "hasu",
    name: "Lotus",
    ja: "蓮",
    reading: "hasu",
    kanji: "蓮",
    category: "flower",
    meaning: "Purity out of mud. The flower of the Buddha's seat.",
    lore: "The lotus rises clean out of still, dirty water, which is why it sits under deities and above koi ponds. Calmer than the peony; pink, white or pale blue. Good on the sternum and the top of the foot.",
    sessions: [1, 4],
    placements: ["Sternum", "Foot", "Shoulder"],
    pairsWith: ["koi", "fudo", "nami"],
    method: "both",
    tone: "paper",
  },
  {
    slug: "ume",
    name: "Plum blossom",
    ja: "梅",
    reading: "ume",
    kanji: "梅",
    category: "flower",
    meaning: "Endurance. The first flower to open, while there is still snow.",
    lore: "Plum blossoms on bare branches are the winter flower, five round petals rather than the cherry's notched ones. They give a piece a season and a quieter mood than sakura.",
    sessions: [1, 3],
    placements: ["Forearm", "Collarbone", "Filler"],
    pairsWith: ["tsuru", "hebi", "kaze"],
    method: "both",
    tone: "paper",
  },
  {
    slug: "nami",
    name: "Waves",
    ja: "波",
    reading: "nami",
    kanji: "波",
    category: "water",
    meaning: "Motion and change. The background that binds a body suit together.",
    lore: "Water is the connective tissue of Japanese tattooing. It fills the space between creatures, it gives the piece direction, and the fingers of foam are where you can tell one artist from another. Plan it early; it decides the shape of everything else.",
    sessions: [2, 12],
    placements: ["Background for any piece", "Full sleeve", "Legs"],
    pairsWith: ["koi", "ryu", "momiji"],
    method: "tebori",
    tone: "ink",
  },
  {
    slug: "kaze",
    name: "Wind bars",
    ja: "風",
    reading: "kaze",
    kanji: "風",
    category: "water",
    meaning: "Movement without water. The black bars that make a sleeve read as one piece.",
    lore: "Wind bars are the bands of black that sweep behind tigers, flowers and guardians when water would not make sense. They are almost always tebori-shaded and are the fastest way to make a collection of separate tattoos into a single sleeve.",
    sessions: [2, 8],
    placements: ["Background for sleeves", "Back", "Legs"],
    pairsWith: ["tora", "karajishi", "botan"],
    method: "tebori",
    tone: "ink",
  },
  {
    slug: "hannya",
    name: "Hannya",
    ja: "般若",
    reading: "hannya",
    kanji: "般若",
    category: "guardian",
    meaning: "The mask of a woman turned demon by jealousy. Also a ward against evil.",
    lore: "The Noh mask is drawn so that it looks furious from the front and grieving when tilted, and a good tattoo keeps both. Horns, a wide mouth, metal-leaf eyes. Red for the fiercest version, white or pale for the more sorrowful one.",
    sessions: [2, 5],
    placements: ["Forearm", "Calf", "Shoulder", "Thigh"],
    pairsWith: ["kaze", "sakura", "hebi"],
    method: "both",
    tone: "deep",
  },
  {
    slug: "fudo",
    name: "Fudō Myōō",
    ja: "不動明王",
    reading: "Fudō Myōō",
    kanji: "不動",
    category: "guardian",
    meaning: "The immovable wisdom king: sword, rope, and a halo of flame.",
    lore: "Fudō sits or stands on a rock, scowling, with fire behind him and the sword that cuts through ignorance in his right hand. The most serious of the deity motifs and one of the few that fills a whole back on its own. Tebori work, plural sessions, patience.",
    sessions: [6, 16],
    placements: ["Back", "Chest and stomach"],
    pairsWith: ["hasu", "iwa", "kumo"],
    method: "tebori",
    tone: "ink",
  },
  {
    slug: "tengu",
    name: "Tengu",
    ja: "天狗",
    reading: "tengu",
    kanji: "天狗",
    category: "guardian",
    meaning: "The mountain spirit: proud, dangerous, a teacher of swordsmen.",
    lore: "Red face, long nose, feather fan, and sometimes wings. Tengu punish arrogance and, in some stories, taught martial arts to those who climbed to find them. A strong shoulder or thigh piece with plenty of room for wind.",
    sessions: [3, 8],
    placements: ["Shoulder", "Thigh", "Back"],
    pairsWith: ["kaze", "matsu", "kumo"],
    method: "both",
    tone: "deep",
  },
  {
    slug: "oni",
    name: "Oni",
    ja: "鬼",
    reading: "oni",
    kanji: "鬼",
    category: "guardian",
    meaning: "The demon at the gate. Frightening on purpose, to keep worse things away.",
    lore: "Horns, tusks, a club, skin in red or blue. Oni are punishers rather than pure evil, and wearing one is a way of saying you can carry your own bad luck. Faces work at any size; full figures need a shoulder or back.",
    sessions: [2, 8],
    placements: ["Forearm", "Calf", "Shoulder", "Back"],
    pairsWith: ["kaze", "sakura", "iwa"],
    method: "both",
    tone: "deep",
  },
  {
    slug: "kumo",
    name: "Clouds",
    ja: "雲",
    reading: "kumo",
    kanji: "雲",
    category: "background",
    meaning: "The sky behind dragons and deities. Softens every hard edge.",
    lore: "Clouds are drawn as scrolling, layered shapes with clean black edges and grey shading inside. They separate a dragon from the wind and give a deity somewhere to stand. Usually tebori, because the gradients are what make them work.",
    sessions: [2, 10],
    placements: ["Background for any piece"],
    pairsWith: ["ryu", "fudo", "tsuru"],
    method: "tebori",
    tone: "ink",
  },
  {
    slug: "iwa",
    name: "Rocks",
    ja: "岩",
    reading: "iwa",
    kanji: "岩",
    category: "background",
    meaning: "Ground. Something for a guardian to stand on and water to break against.",
    lore: "Angular, grey, quick to tattoo and easy to overlook until they are missing. Rocks anchor a composition at the bottom of a piece so the eye has somewhere to rest.",
    sessions: [1, 6],
    placements: ["Bottom of sleeves and legs", "Base of back pieces"],
    pairsWith: ["fudo", "karajishi", "nami"],
    method: "both",
    tone: "ink",
  },
  {
    slug: "take",
    name: "Bamboo",
    ja: "竹",
    reading: "take",
    kanji: "竹",
    category: "background",
    meaning: "Strength that bends. The tiger's forest.",
    lore: "Bamboo is drawn in straight jointed stalks with leaves in threes. It is the traditional companion of the tiger and fills vertical space on a leg or the side of the torso without competing with the main figure.",
    sessions: [1, 4],
    placements: ["Behind tigers", "Ribs", "Legs"],
    pairsWith: ["tora", "kaze", "tsuru"],
    method: "both",
    tone: "paper",
  },
  {
    slug: "matsu",
    name: "Pine",
    ja: "松",
    reading: "matsu",
    kanji: "松",
    category: "background",
    meaning: "Steadfastness. Green through every winter.",
    lore: "Pine appears with cranes and at New Year. In tattooing it is a background of dense needle clusters and gnarled trunk, more work than it looks and worth it on a back piece that needs weight at the edges.",
    sessions: [2, 6],
    placements: ["Back", "Shoulder", "Behind cranes"],
    pairsWith: ["tsuru", "tengu", "kumo"],
    method: "tebori",
    tone: "deep",
  },
  {
    slug: "kaen",
    name: "Flames",
    ja: "火焔",
    reading: "kaen",
    kanji: "火",
    category: "background",
    meaning: "Purifying fire. The heat that burns off what holds you back.",
    lore: "Flames rise behind Fudō and curl around dragons and hannya. As a background they do the job clouds do for creatures, but with more drama: tongues of vermilion drawn in tight scrolls that lead the eye up the back.",
    sessions: [1, 5],
    placements: ["Back", "Behind guardians", "Sleeve"],
    pairsWith: ["fudo", "ryu", "hannya"],
    method: "both",
    tone: "ink",
  },
];

// Where each on-body photo places the tattoo (checked against the generated photos).
const wornOn: Record<string, string> = {
  koi: "the upper arm", ryu: "the back", tora: "the hip and thigh", hebi: "the forearm",
  tsuru: "the upper back", kitsune: "the calf", karajishi: "the thigh", botan: "the hip",
  sakura: "the collarbone", kiku: "the leg", momiji: "the ankle", hasu: "the top of the foot",
  ume: "the forearm", nami: "a full sleeve", kaze: "the leg", hannya: "the shoulder",
  fudo: "the chest", tengu: "the thigh", oni: "the forearm", kumo: "the shoulder",
  iwa: "the lower back", take: "the ribs", matsu: "the upper back", kaen: "the upper arm",
};

// Plates generated by scripts/motif-art.mjs live in public/motifs/<slug>.webp;
// on-body photos from scripts/worn-art.mjs in public/motifs/worn/<slug>.webp.
export const motifs: Motif[] = raw.map((m) => ({
  ...m,
  image: `/motifs/${m.slug}.webp`,
  worn: `/motifs/worn/${m.slug}.webp`,
  wornOn: wornOn[m.slug],
}));

export const featuredMotifs = ["koi", "ryu", "botan", "nami", "tora", "hannya"].map(
  (slug) => motifs.find((m) => m.slug === slug)!,
);

export function getMotif(slug: string) {
  return motifs.find((m) => m.slug === slug);
}

export function categoryOf(id: MotifCategory) {
  return categories.find((c) => c.id === id)!;
}

export function methodOf(id: Method) {
  return methods.find((m) => m.id === id)!;
}
